# Generated by Django 5.0.2 on 2024-05-12 18:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('manager', '0003_department_is_visible'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('devision', models.CharField(choices=[('Regular', 'Regular'), ('Extension', 'Extension')], max_length=50)),
                ('programme', models.CharField(choices=[('Degree', 'Degree'), ('Masters', 'Masters')], max_length=50)),
                ('phone_no', models.CharField(blank=True, max_length=10, null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manager.batch')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manager.department')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.section')),
            ],
        ),
        migrations.CreateModel(
            name='AbsentNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.period')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
        ),
    ]
