# Generated by Django 5.0.2 on 2024-05-27 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_remove_student_department_alter_student_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='batch',
        ),
    ]
