# Generated by Django 5.0.2 on 2024-05-12 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
    ]
