# Generated by Django 5.0.2 on 2024-05-12 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_batch_is_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
    ]
