# Generated by Django 5.0.2 on 2024-05-13 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_department_is_visible'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='semester',
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semster_number', models.IntegerField(blank=True, null=True)),
                ('starting_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='manager.batch')),
            ],
        ),
        migrations.AddField(
            model_name='timetable',
            name='semster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='manager.semester'),
        ),
    ]
