# Generated by Django 5.0.2 on 2024-05-19 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_remove_timetable_semester_semester_timetable_semster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manager.department'),
        ),
    ]
