# Generated by Django 5.0.2 on 2024-05-23 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_alter_section_batch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='period',
            name='class_room',
        ),
    ]
