# Generated by Django 5.0.2 on 2024-05-27 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0009_alter_section_devision'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
    ]
